### PR TITLE
chore(release): 0.1.1

### LINKED ISSUE #90: Cannot render swagger spec file
Hi 

I am using hexo-theme-doc with hexo-theme-doc-seed. I keep 

## Expected Behavior
Render this swagger specification file:
https://zalando-incubator.github.io/hexo-theme-doc/f20a00536303efe9f480416cc6f09e32/petstore.yaml

to get this page
https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/swagger/swagger-ui.html#/pets/findPets

## Actual Behavior
Getting error in attached image. Cannot seem to resolve relative references such as 
$ref: '#/parameters/Authorization
selection_977

Markdown file contains only reference to spec file 

{% swagger_ui ./spec/petstore.yaml %}

## Steps to Reproduce the Problem

  1. Save spec file located here: https://zalando-incubator.github.io/hexo-theme-doc/f20a00536303efe9f480416cc6f09e32/petstore.yaml
  2. create a markdown file with swagger tags and reference to downloaded file - for example {% swagger_ui ./spec/petstore.yaml %}
  3. Check to see if page is rendered

## Specifications

  - NodeJS Version: v8.9.0
  - NPM Version: 5.5.1
  - OS:  DISTRIB_ID=LinuxMint   DISTRIB_RELEASE=17.1
  - Hexo Version: 3.4.3

Also have the latest version of hexo-theme-docs which refers to npm version of hexo-doc rather than git repo

 Hexo version output: 

- hexo: 3.4.3
- hexo-cli: 1.0.4
- os: Linux 3.13.0-37-generic linux x64
- http_parser: 2.7.0
- node: 8.9.0
- v8: 6.1.534.46
- uv: 1.15.0
- zlib: 1.2.11
- ares: 1.10.1-DEV
- modules: 57
- nghttp2: 1.25.0
- openssl: 1.0.2l
- icu: 59.1
- unicode: 9.0
- cldr: 31.0.1
- tz: 2017b

### PR DESCRIPTION
**Pull request by bhaskarmelkani**
chore(release): 0.1.0

Closes #90

### CODE REVIEW

**Comment by bhaskarmelkani** [comment]
👍

**Comment by rbarilani** [comment]
@bhaskarmelkani Commit message and PR description title is not correct, should 0.1.1

**Comment by bhaskarmelkani** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Pull request merged**
