### PR TITLE
docs(compliance): Add security file

### LINKED ISSUE #169: Add Security.md file.
Add security.md file to be compliant.

### PR DESCRIPTION
**Pull request by bhaskarmelkani**
Add security.md file to be compliant.

Closes #169

### CODE REVIEW

**Comment by bhaskarmelkani** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@bhaskarmelkani Can you squash your commit message using the "right" prefix: "docs: ass security file"

**Comment by bhaskarmelkani** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by bhaskarmelkani** [comment]
👍

**Pull request merged**
